### ISSUE TITLE
after cmake .. step no binary file was found 

### ISSUE THREAD

**Issue by deleep225** [a-anik/cavity-volumes-pbc#1]

**Comment by a-anik** [comment]
Thank you for your feedback!  You are right. Binary file should be created after the final `make` command, which I missed out in my quick steps guide.

**Comment by deleep225** [comment]
thank you.

**Comment by deleep225** [comment]
respected sir,
I am using vnp software to calculate the void radii. (windows)
I have provided the coordinates and the radii of atoms of ionic liquid.
(all atom)

I considered the van der Waals radius of atoms.
I am getting negative values of radii.
Is there anything wrong in my procedure.
Thank you for your time.

**Comment by a-anik** [comment]
It totally makes sense. What you get is actually a _weight_ in additively-weighted Voronoi diagram. It can be negative. In that case it means that the "inscribed" sphere for the tetrahedron is covered by its atoms and touches them from the inside. No void space is contained in such Delaunay simplexes. Only positive radii correspond to real empty inscribed spheres.

**Comment by deleep225** [comment]
Thanks for your kind reply.
In that case,
I have calculated the distribution for only positive values.

The graph I have attached.

My system is pyrrolidinium TFSI ionic liquid.

I am trying to calculate the distribution of interstitial spheres similar
to
"Comparing the void space and long-range structure of an ionic liquid
with a neutral mixture of similar sized molecules"

Kindly can you comment on my result as I am doing it first time.
I am very grateful for your help.
