### ISSUE TITLE
make gives error

### ISSUE THREAD

**Issue by sathishdasari** [a-anik/cavity-volumes-pbc#2]
I was trying to install cavity-volumes-pbc.
I followed the steps as suggested.

I installed CGAL-5.0
$ git clone http://github.com/a-anik/cavity-volumes-pbc.git
$ cd cavity-volumes-pbc
$ mkdir build
$ cd build
$ cmake ..
After this I was trying to use make to generate the executable, but I get the following error

/usr/local/include/CGAL/Kernel/hash_functions.h:25:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:47:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:57:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:66:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:75:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:84:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:93:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:102:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:126:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:135:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:145:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:154:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:164:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
/usr/local/include/CGAL/Kernel/hash_functions.h:174:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
        ^
In file included from /usr/local/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/local/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/local/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/local/include/CGAL/Filtered_kernel.h:22,
                 from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/sathish/Softwares/cavity-volumes-pbc/cavity_volumes_pbc.cpp:16:
/usr/local/include/CGAL/Lazy.h:108:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, T> approx(T d){return d;}
                         ^
/usr/local/include/CGAL/Lazy.h:109:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, T> exact (T d){return d;}
                         ^
/usr/local/include/CGAL/Lazy.h:110:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_arithmetic<T>::value||std::is_enum<T>::value, unsigned> depth(T){return 0;}
                         ^
/usr/local/include/CGAL/Lazy.h:113:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, T> exact(T){return {};}
                         ^
/usr/local/include/CGAL/Lazy.h:114:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, T> approx(T){return {};}
                         ^
/usr/local/include/CGAL/Lazy.h:115:25: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 template<class T>inline std::enable_if_t<std::is_empty<T>::value, unsigned> depth(T){return 0;}
                         ^
/usr/local/include/CGAL/Lazy.h:118:26: error: expected type-specifier
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                          ^
/usr/local/include/CGAL/Lazy.h:118:26: error: expected ‘>’
/usr/local/include/CGAL/Lazy.h: In function ‘auto CGAL::exact(const T&)’:
/usr/local/include/CGAL/Lazy.h:119:75: error: parameter declared ‘auto’
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                                                                           ^
/usr/local/include/CGAL/Lazy.h: In lambda function:
/usr/local/include/CGAL/Lazy.h:119:97: error: ‘u’ was not declared in this scope
 auto exact(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::exact(u);});}
                                                                                                 ^
/usr/local/include/CGAL/Lazy.h: At global scope:
/usr/local/include/CGAL/Lazy.h:120:26: error: expected type-specifier
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                          ^
/usr/local/include/CGAL/Lazy.h:120:26: error: expected ‘>’
/usr/local/include/CGAL/Lazy.h: In function ‘auto CGAL::approx(const T&)’:
/usr/local/include/CGAL/Lazy.h:121:76: error: parameter declared ‘auto’
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                            ^
/usr/local/include/CGAL/Lazy.h: In lambda function:
/usr/local/include/CGAL/Lazy.h:121:99: error: ‘u’ was not declared in this scope
 auto approx(T const& t) {return make_transforming_iterator(t,[](auto const&u){return CGAL::approx(u);});}
                                                                                                   ^
/usr/local/include/CGAL/Lazy.h: At global scope:
/usr/local/include/CGAL/Lazy.h:122:26: error: expected type-specifier
 template <class T, class=std::enable_if_t<is_iterator_type<T,std::input_iterator_tag>::value>>
                          ^
/usr/local/include/CGAL/Lazy.h:122:26: error: expected ‘>’
In file included from /usr/local/include/CGAL/Lazy_exact_nt.h:33:0,
                 from /usr/local/include/CGAL/internal/Exact_type_selector.h:25,
                 from /usr/local/include/CGAL/Exact_kernel_selector.h:26,
                 from /usr/local/include/CGAL/Filtered_kernel.h:22,
                 from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from /home/sathish/Softwares/cavity-volumes-pbc/cavity_volumes_pbc.cpp:16:
/usr/local/include/CGAL/Lazy.h:320:33: error: ‘std::index_sequence’ has not been declared
   void update_exact_helper(std::index_sequence<I...>) const {
                                 ^
/usr/local/include/CGAL/Lazy.h:320:47: error: expected ‘,’ or ‘...’ before ‘<’ token
   void update_exact_helper(std::index_sequence<I...>) const {
                                               ^
/usr/local/include/CGAL/Lazy.h: In member function ‘void CGAL::Lazy_rep_n<AT, ET, AC, EC, E2A, L>::update_exact() const’:
/usr/local/include/CGAL/Lazy.h:327:25: error: ‘make_index_sequence’ is not a member of ‘std’
     update_exact_helper(std::make_index_sequence<sizeof...(L)>{});
                         ^
/usr/local/include/CGAL/Lazy.h:327:63: error: expected primary-expression before ‘{’ token
     update_exact_helper(std::make_index_sequence<sizeof...(L)>{});
                                                               ^
/usr/local/include/CGAL/Lazy.h: At global scope:
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                 ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/local/include/CGAL/Lazy.h:831:34: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                  ^
/usr/local/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                 ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/local/include/CGAL/Lazy.h:831:34: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                  ^
/usr/local/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                 ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/local/include/CGAL/Lazy.h:831:34: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                  ^
/usr/local/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                 ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/local/include/CGAL/Lazy.h:831:34: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                  ^
/usr/local/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                 ^
/usr/local/include/CGAL/Lazy.h:831:17: error: ‘remove_cv_t’ is not a member of ‘std’
/usr/local/include/CGAL/Lazy.h:831:34: error: ‘remove_reference_t’ is not a member of ‘std’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                  ^
/usr/local/include/CGAL/Lazy.h:831:89: error: template argument 1 is invalid
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
                                                                                         ^
/usr/local/include/CGAL/Lazy.h:831:3: error: expected type-specifier before ‘Lazy_exact_nt’
   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
   ^
/usr/local/include/CGAL/Lazy.h:831:3: error: expected initializer before ‘Lazy_exact_nt’
In file included from /usr/local/include/CGAL/Triangulation_data_structure_3.h:34:0,
                 from /usr/local/include/CGAL/Triangulation_3.h:38,
                 from /usr/local/include/CGAL/Regular_triangulation_3.h:40,
                 from /home/sathish/Softwares/cavity-volumes-pbc/cavity_volumes_pbc.cpp:17:
/usr/local/include/CGAL/iterator.h:663:11: error: ‘decay_t’ in namespace ‘std’ does not name a type
   typedef std::decay_t<typename cpp11::result_of<Op(arg_type)>::type> value_type;
           ^
/usr/local/include/CGAL/iterator.h:665:11: error: ‘value_type’ does not name a type
   typedef value_type const*                                     pointer;
           ^
/usr/local/include/CGAL/iterator.h:666:11: error: ‘value_type’ does not name a type
   typedef value_type const&                                     reference;
           ^
/usr/local/include/CGAL/iterator.h:671:11: error: ‘value_type’ does not name a type
   mutable value_type val;  // Note: mutable is needed because we want to
           ^
/usr/local/include/CGAL/iterator.h:699:9: error: ‘value_type’ does not name a type
   const value_type& operator*() const { 
         ^
/usr/local/include/CGAL/iterator.h:715:9: error: ‘value_type’ does not name a type
   const value_type& operator[](difference_type i) const {
         ^
/usr/local/include/CGAL/iterator.h:1321:44: error: ‘std::index_sequence’ has not been declared
 auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                            ^
/usr/local/include/CGAL/iterator.h:1321:58: error: expected ‘,’ or ‘...’ before ‘<’ token
 auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                                          ^
/usr/local/include/CGAL/iterator.h: In member function ‘CGAL::Dispatch_output_iterator<std::tuple<_Elements ...>, std::tuple<_Elements ...> >::operator std::tuple<O& ...>()’:
/usr/local/include/CGAL/iterator.h:1414:44: error: ‘index_sequence_for’ is not a member of ‘std’
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                            ^
/usr/local/include/CGAL/iterator.h:1414:69: error: expected primary-expression before ‘...’ token
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                     ^
/usr/local/include/CGAL/iterator.h: In member function ‘CGAL::Dispatch_output_iterator<std::tuple<_Elements ...>, std::tuple<_Elements ...> >::operator std::tuple<const O& ...>() const’:
/usr/local/include/CGAL/iterator.h:1419:44: error: ‘index_sequence_for’ is not a member of ‘std’
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                            ^
/usr/local/include/CGAL/iterator.h:1419:69: error: expected primary-expression before ‘...’ token
     return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                     ^
make[2]: *** [CMakeFiles/cavity_volumes_pbc.dir/cavity_volumes_pbc.cpp.o] Error 1
make[1]: *** [CMakeFiles/cavity_volumes_pbc.dir/all] Error 2
make: *** [all] Error 2

what could be the problem

**Comment by a-anik** [comment]
It looks like CGAL & compiler issue. Are you able to build CGAL's examples with this compiler? Is it listed in https://doc.cgal.org/latest/Manual/thirdparty.html#seccompilers? I've just built the project using g++-7 and CGAL-5.0 without any problems.

**Comment by sathishdasari** [comment]
Thanks a-anik

Its working now
